version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION:-8.3}
        - XDEBUG=${XDEBUG:-0}
    volumes:
      - ./:/docker
    networks:
      - telnyx-net 
    environment:
      TELNYX_MOCK_HOST: ${TELNYX_MOCK_HOST}
      TELNYX_MOCK_PORT: ${TELNYX_MOCK_PORT}
      TELNYX_MOCK_OPEN_API_URI: ${TELNYX_MOCK_OPEN_API_URI}
    command: composer test
networks:
  telnyx-net:
    driver: bridge
